"""
Stealth JavaScript Injection Scripts for Anti-Detection

Generates JavaScript code to spoof all browser fingerprint surfaces.
Works with Playwright's add_init_script() for injection before page load.

Usage:
    from stealth_scripts import StealthScripts
    from fingerprint_generator import FingerprintGenerator
    
    fp = FingerprintGenerator.generate()
    js_code = StealthScripts.generate_all(fp)
    
    # In Playwright:
    await context.add_init_script(js_code)
"""
from typing import Dict, List
import json
import logging

logger = logging.getLogger(__name__)


class StealthScripts:
    """Generate stealth JavaScript for fingerprint spoofing."""
    
    @classmethod
    def generate_all(cls, fingerprint) -> str:
        """
        Generate complete stealth script for all fingerprint surfaces.
        
        Args:
            fingerprint: BrowserFingerprint instance
            
        Returns:
            Complete JavaScript code to inject
        """
        scripts = [
            cls._header(),
            cls._navigator_overrides(fingerprint),
            cls._screen_overrides(fingerprint),
            cls._webgl_overrides(fingerprint),
            cls._canvas_noise(fingerprint),
            cls._audio_noise(fingerprint),
            cls._webrtc_protection(fingerprint),
            cls._timezone_override(fingerprint),
            cls._media_devices_override(fingerprint),
            cls._client_rects_noise(fingerprint),
            cls._plugins_override(fingerprint),
            cls._permissions_override(),
            cls._misc_overrides(fingerprint),
            cls._footer(),
        ]
        
        return "\n\n".join(scripts)
    
    @classmethod
    def _header(cls) -> str:
        """Script header with error handling."""
        return """
// ========================================
// Anti-Detection Stealth Script
// Generated by k12_verify fingerprint system
// ========================================

(function() {
    'use strict';
    
    // Helper to define non-configurable property
    const defineProperty = (obj, prop, value) => {
        try {
            Object.defineProperty(obj, prop, {
                get: () => value,
                configurable: true
            });
        } catch (e) {}
    };
    
    // Helper for function spoofing
    const spoofFunction = (obj, prop, fake) => {
        const original = obj[prop];
        obj[prop] = function(...args) {
            return fake.apply(this, [original.bind(this), ...args]);
        };
        obj[prop].toString = () => `function ${prop}() { [native code] }`;
    };
"""

    @classmethod
    def _footer(cls) -> str:
        """Script footer."""
        return """
    // ========================================
    // Stealth script loaded successfully
    // ========================================
    
})();
"""

    @classmethod
    def _navigator_overrides(cls, fp) -> str:
        """Override navigator properties."""
        languages_json = json.dumps(fp.languages)
        
        return f"""
    // === Navigator Overrides ===
    
    // Remove webdriver flag (most important!)
    defineProperty(navigator, 'webdriver', undefined);
    
    // Hardware info
    defineProperty(navigator, 'hardwareConcurrency', {fp.hardware_concurrency});
    defineProperty(navigator, 'deviceMemory', {fp.device_memory});
    defineProperty(navigator, 'maxTouchPoints', {fp.max_touch_points});
    
    // Platform & vendor
    defineProperty(navigator, 'platform', '{fp.platform}');
    defineProperty(navigator, 'vendor', '{fp.vendor}');
    defineProperty(navigator, 'vendorSub', '{fp.vendor_sub}');
    defineProperty(navigator, 'product', '{fp.product}');
    defineProperty(navigator, 'productSub', '{fp.product_sub}');
    defineProperty(navigator, 'appName', '{fp.app_name}');
    defineProperty(navigator, 'appCodeName', '{fp.app_code_name}');
    
    // Language
    defineProperty(navigator, 'language', '{fp.language}');
    defineProperty(navigator, 'languages', Object.freeze({languages_json}));
    
    // Cookie & Java
    defineProperty(navigator, 'cookieEnabled', {str(fp.cookie_enabled).lower()});
    defineProperty(navigator, 'javaEnabled', () => {str(fp.java_enabled).lower()});
    defineProperty(navigator, 'pdfViewerEnabled', {str(fp.pdf_viewer_enabled).lower()});
    
    // Do Not Track
    defineProperty(navigator, 'doNotTrack', {'null' if fp.do_not_track is None else f'"{fp.do_not_track}"'});
    
    // Connection info (fake fast connection)
    if (navigator.connection) {{
        defineProperty(navigator.connection, 'effectiveType', '4g');
        defineProperty(navigator.connection, 'downlink', 10);
        defineProperty(navigator.connection, 'rtt', 50);
    }}
"""

    @classmethod
    def _screen_overrides(cls, fp) -> str:
        """Override screen properties."""
        return f"""
    // === Screen Overrides ===
    
    defineProperty(screen, 'width', {fp.screen_width});
    defineProperty(screen, 'height', {fp.screen_height});
    defineProperty(screen, 'availWidth', {fp.screen_avail_width});
    defineProperty(screen, 'availHeight', {fp.screen_avail_height});
    defineProperty(screen, 'colorDepth', {fp.color_depth});
    defineProperty(screen, 'pixelDepth', {fp.pixel_depth});
    
    // Window dimensions
    defineProperty(window, 'devicePixelRatio', {fp.device_pixel_ratio});
    defineProperty(window, 'innerWidth', {fp.screen_width});
    defineProperty(window, 'innerHeight', {fp.screen_avail_height});
    defineProperty(window, 'outerWidth', {fp.screen_width});
    defineProperty(window, 'outerHeight', {fp.screen_height});
"""

    @classmethod
    def _webgl_overrides(cls, fp) -> str:
        """Override WebGL vendor and renderer."""
        # Escape special characters in renderer string
        webgl_vendor = fp.webgl_vendor.replace("'", "\\'")
        webgl_renderer = fp.webgl_renderer.replace("'", "\\'")
        
        return f"""
    // === WebGL Overrides ===
    
    const webglVendor = '{webgl_vendor}';
    const webglRenderer = '{webgl_renderer}';
    
    // WebGL1
    const getParameterOrig = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function(param) {{
        // UNMASKED_VENDOR_WEBGL
        if (param === 37445) return webglVendor;
        // UNMASKED_RENDERER_WEBGL
        if (param === 37446) return webglRenderer;
        return getParameterOrig.call(this, param);
    }};
    
    // WebGL2
    if (typeof WebGL2RenderingContext !== 'undefined') {{
        const getParameter2Orig = WebGL2RenderingContext.prototype.getParameter;
        WebGL2RenderingContext.prototype.getParameter = function(param) {{
            if (param === 37445) return webglVendor;
            if (param === 37446) return webglRenderer;
            return getParameter2Orig.call(this, param);
        }};
    }}
    
    // Debug info extension
    const origGetExtension = WebGLRenderingContext.prototype.getExtension;
    WebGLRenderingContext.prototype.getExtension = function(name) {{
        const ext = origGetExtension.call(this, name);
        if (name === 'WEBGL_debug_renderer_info' && ext) {{
            return {{
                UNMASKED_VENDOR_WEBGL: 37445,
                UNMASKED_RENDERER_WEBGL: 37446
            }};
        }}
        return ext;
    }};
"""

    @classmethod
    def _canvas_noise(cls, fp) -> str:
        """Add noise to canvas fingerprint."""
        return f"""
    // === Canvas Fingerprint Noise ===
    
    const canvasNoiseSeed = {fp.canvas_noise_seed};
    const canvasNoiseFactor = {fp.canvas_noise_factor};
    
    // Simple seeded random
    function seededRandom(seed) {{
        const x = Math.sin(seed++) * 10000;
        return x - Math.floor(x);
    }}
    
    // Override toDataURL
    const originalToDataURL = HTMLCanvasElement.prototype.toDataURL;
    HTMLCanvasElement.prototype.toDataURL = function(type, quality) {{
        // Only add noise if canvas has content
        if (this.width > 0 && this.height > 0) {{
            try {{
                const ctx = this.getContext('2d');
                if (ctx) {{
                    const imageData = ctx.getImageData(0, 0, this.width, this.height);
                    const data = imageData.data;
                    
                    // Add subtle noise
                    for (let i = 0; i < data.length; i += 4) {{
                        const noise = (seededRandom(canvasNoiseSeed + i) - 0.5) * canvasNoiseFactor * 255;
                        data[i] = Math.max(0, Math.min(255, data[i] + noise));     // R
                        data[i+1] = Math.max(0, Math.min(255, data[i+1] + noise)); // G
                        data[i+2] = Math.max(0, Math.min(255, data[i+2] + noise)); // B
                    }}
                    
                    ctx.putImageData(imageData, 0, 0);
                }}
            }} catch (e) {{
                // Canvas tainted, skip noise
            }}
        }}
        return originalToDataURL.call(this, type, quality);
    }};
    
    // Override toBlob
    const originalToBlob = HTMLCanvasElement.prototype.toBlob;
    HTMLCanvasElement.prototype.toBlob = function(callback, type, quality) {{
        // Convert via toDataURL to apply noise
        const dataURL = this.toDataURL(type, quality);
        fetch(dataURL)
            .then(res => res.blob())
            .then(blob => callback(blob));
    }};
    
    // Override getImageData
    const originalGetImageData = CanvasRenderingContext2D.prototype.getImageData;
    CanvasRenderingContext2D.prototype.getImageData = function(sx, sy, sw, sh) {{
        const imageData = originalGetImageData.call(this, sx, sy, sw, sh);
        const data = imageData.data;
        
        // Add noise
        for (let i = 0; i < data.length; i += 4) {{
            const noise = (seededRandom(canvasNoiseSeed + i) - 0.5) * canvasNoiseFactor * 255;
            data[i] = Math.max(0, Math.min(255, data[i] + noise));
        }}
        
        return imageData;
    }};
"""

    @classmethod
    def _audio_noise(cls, fp) -> str:
        """Add noise to audio fingerprint."""
        return f"""
    // === Audio Fingerprint Noise ===
    
    const audioNoiseSeed = {fp.audio_noise_seed};
    const audioNoiseFactor = {fp.audio_noise_factor};
    
    // Override AudioContext
    if (typeof AudioContext !== 'undefined') {{
        const OriginalAudioContext = AudioContext;
        
        // Override sample rate
        Object.defineProperty(AudioContext.prototype, 'sampleRate', {{
            get: function() {{ return {fp.audio_context_sample_rate}; }}
        }});
        
        // Override getChannelData to add noise
        const originalGetChannelData = AudioBuffer.prototype.getChannelData;
        AudioBuffer.prototype.getChannelData = function(channel) {{
            const data = originalGetChannelData.call(this, channel);
            
            // Add subtle noise
            for (let i = 0; i < data.length; i++) {{
                const noise = (seededRandom(audioNoiseSeed + i) - 0.5) * audioNoiseFactor;
                data[i] = data[i] + noise;
            }}
            
            return data;
        }};
    }}
    
    // OfflineAudioContext
    if (typeof OfflineAudioContext !== 'undefined') {{
        const OriginalOfflineAudioContext = OfflineAudioContext;
        
        // Override to add noise to rendered buffer
        const originalStartRendering = OfflineAudioContext.prototype.startRendering;
        OfflineAudioContext.prototype.startRendering = function() {{
            return originalStartRendering.call(this).then(buffer => {{
                // Noise is already applied via getChannelData override
                return buffer;
            }});
        }};
    }}
"""

    @classmethod
    def _webrtc_protection(cls, fp) -> str:
        """WebRTC IP leak protection."""
        if fp.webrtc_mode == "disabled":
            return """
    // === WebRTC Disabled ===
    
    // Completely disable WebRTC
    if (typeof RTCPeerConnection !== 'undefined') {
        window.RTCPeerConnection = undefined;
    }
    if (typeof webkitRTCPeerConnection !== 'undefined') {
        window.webkitRTCPeerConnection = undefined;
    }
    if (typeof mozRTCPeerConnection !== 'undefined') {
        window.mozRTCPeerConnection = undefined;
    }
    
    // Also remove from navigator
    if (navigator.mediaDevices) {
        navigator.mediaDevices.getUserMedia = undefined;
    }
"""
        elif fp.webrtc_mode == "altered":
            return f"""
    // === WebRTC Altered (IP Masked) ===
    
    const spoofedLocalIP = '{fp.webrtc_local_ip}';
    
    if (typeof RTCPeerConnection !== 'undefined') {{
        const OriginalRTCPeerConnection = RTCPeerConnection;
        
        window.RTCPeerConnection = function(config, constraints) {{
            // Force STUN/TURN only (no local candidates)
            if (config && config.iceServers) {{
                config.iceCandidatePoolSize = 0;
            }}
            
            const pc = new OriginalRTCPeerConnection(config, constraints);
            
            // Override onicecandidate to filter local IPs
            const originalSetOnIceCandidate = Object.getOwnPropertyDescriptor(
                RTCPeerConnection.prototype, 'onicecandidate'
            );
            
            Object.defineProperty(pc, 'onicecandidate', {{
                set: function(handler) {{
                    if (handler) {{
                        const wrappedHandler = function(event) {{
                            if (event.candidate) {{
                                // Replace real local IP with spoofed one
                                const sdp = event.candidate.candidate;
                                if (sdp && (sdp.includes('192.168.') || sdp.includes('10.') || sdp.includes('172.'))) {{
                                    // Skip local IP candidates or modify them
                                    const modified = sdp.replace(
                                        /([0-9]{{1,3}}\.[0-9]{{1,3}}\.[0-9]{{1,3}}\.[0-9]{{1,3}})/g,
                                        spoofedLocalIP
                                    );
                                    event = {{
                                        ...event,
                                        candidate: {{
                                            ...event.candidate,
                                            candidate: modified
                                        }}
                                    }};
                                }}
                            }}
                            handler.call(this, event);
                        }};
                        originalSetOnIceCandidate.set.call(this, wrappedHandler);
                    }} else {{
                        originalSetOnIceCandidate.set.call(this, handler);
                    }}
                }},
                get: function() {{
                    return originalSetOnIceCandidate.get.call(this);
                }}
            }});
            
            return pc;
        }};
        
        // Copy prototype
        window.RTCPeerConnection.prototype = OriginalRTCPeerConnection.prototype;
    }}
"""
        else:
            return """
    // === WebRTC Real (No Protection) ===
    // WebRTC is not modified
"""

    @classmethod
    def _timezone_override(cls, fp) -> str:
        """Override timezone."""
        return f"""
    // === Timezone Override ===
    
    const spoofedTimezone = '{fp.timezone}';
    const spoofedOffset = {fp.timezone_offset};
    
    // Override getTimezoneOffset
    const originalGetTimezoneOffset = Date.prototype.getTimezoneOffset;
    Date.prototype.getTimezoneOffset = function() {{
        return spoofedOffset;
    }};
    
    // Override Intl.DateTimeFormat
    const OriginalDateTimeFormat = Intl.DateTimeFormat;
    Intl.DateTimeFormat = function(locales, options) {{
        options = options || {{}};
        options.timeZone = options.timeZone || spoofedTimezone;
        return new OriginalDateTimeFormat(locales, options);
    }};
    Intl.DateTimeFormat.prototype = OriginalDateTimeFormat.prototype;
    
    // Override resolvedOptions
    const originalResolvedOptions = Intl.DateTimeFormat.prototype.resolvedOptions;
    Intl.DateTimeFormat.prototype.resolvedOptions = function() {{
        const options = originalResolvedOptions.call(this);
        options.timeZone = spoofedTimezone;
        return options;
    }};
"""

    @classmethod
    def _media_devices_override(cls, fp) -> str:
        """Override media devices enumeration."""
        devices_json = json.dumps(fp.media_devices)
        
        return f"""
    // === Media Devices Override ===
    
    const spoofedDevices = {devices_json};
    
    if (navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {{
        const originalEnumerateDevices = navigator.mediaDevices.enumerateDevices.bind(navigator.mediaDevices);
        
        navigator.mediaDevices.enumerateDevices = function() {{
            return Promise.resolve(spoofedDevices.map(d => ({{
                deviceId: d.deviceId,
                kind: d.kind,
                label: d.label,
                groupId: d.deviceId.substring(0, 16),
                toJSON: function() {{ return this; }}
            }})));
        }};
    }}
"""

    @classmethod
    def _client_rects_noise(cls, fp) -> str:
        """Add noise to client rects (element dimensions)."""
        return f"""
    // === Client Rects Noise ===
    
    const rectsNoiseSeed = {fp.client_rects_noise_seed};
    const rectsNoiseFactor = {fp.client_rects_noise_factor};
    
    // Override getBoundingClientRect
    const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
    Element.prototype.getBoundingClientRect = function() {{
        const rect = originalGetBoundingClientRect.call(this);
        
        // Add subtle noise to dimensions
        const noise = (seededRandom(rectsNoiseSeed + this.tagName.charCodeAt(0)) - 0.5) * rectsNoiseFactor;
        
        return new DOMRect(
            rect.x + noise,
            rect.y + noise,
            rect.width + noise,
            rect.height + noise
        );
    }};
    
    // Override getClientRects
    const originalGetClientRects = Element.prototype.getClientRects;
    Element.prototype.getClientRects = function() {{
        const rects = originalGetClientRects.call(this);
        const result = [];
        
        for (let i = 0; i < rects.length; i++) {{
            const rect = rects[i];
            const noise = (seededRandom(rectsNoiseSeed + i) - 0.5) * rectsNoiseFactor;
            result.push(new DOMRect(
                rect.x + noise,
                rect.y + noise,
                rect.width + noise,
                rect.height + noise
            ));
        }}
        
        return result;
    }};
"""

    @classmethod
    def _plugins_override(cls, fp) -> str:
        """Override plugins array."""
        return f"""
    // === Plugins Override ===
    
    // Create fake plugins array
    const fakePlugins = [
        {{ name: 'Chrome PDF Plugin', filename: 'internal-pdf-viewer', description: 'Portable Document Format' }},
        {{ name: 'Chrome PDF Viewer', filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai', description: '' }},
        {{ name: 'Native Client', filename: 'internal-nacl-plugin', description: '' }},
        {{ name: 'Chromium PDF Viewer', filename: 'internal-pdf-viewer', description: '' }},
    ];
    
    // Create PluginArray-like object
    const pluginArray = {{}};
    fakePlugins.forEach((p, i) => {{
        const plugin = {{
            name: p.name,
            filename: p.filename,
            description: p.description,
            length: 1,
            item: () => null,
            namedItem: () => null,
            [Symbol.iterator]: function*() {{ yield this; }}
        }};
        pluginArray[i] = plugin;
        pluginArray[p.name] = plugin;
    }});
    
    pluginArray.length = fakePlugins.length;
    pluginArray.item = (i) => pluginArray[i];
    pluginArray.namedItem = (name) => pluginArray[name];
    pluginArray.refresh = () => {{}};
    pluginArray[Symbol.iterator] = function*() {{
        for (let i = 0; i < this.length; i++) yield this[i];
    }};
    
    defineProperty(navigator, 'plugins', pluginArray);
"""

    @classmethod
    def _permissions_override(cls) -> str:
        """Override permissions API."""
        return """
    // === Permissions Override ===
    
    if (navigator.permissions) {
        const originalQuery = navigator.permissions.query.bind(navigator.permissions);
        
        navigator.permissions.query = function(descriptor) {
            // Return 'prompt' for known permissions to seem like clean browser
            const alwaysPrompt = ['notifications', 'push', 'midi'];
            
            if (alwaysPrompt.includes(descriptor.name)) {
                return Promise.resolve({ state: 'prompt', onchange: null });
            }
            
            return originalQuery(descriptor);
        };
    }
"""

    @classmethod
    def _misc_overrides(cls, fp) -> str:
        """Miscellaneous overrides."""
        return f"""
    // === Miscellaneous Overrides ===
    
    // Automation detection properties
    defineProperty(window, 'chrome', {{
        app: {{ isInstalled: false, InstallState: {{ DISABLED: 'disabled', INSTALLED: 'installed', NOT_INSTALLED: 'not_installed' }}, RunningState: {{ CANNOT_RUN: 'cannot_run', READY_TO_RUN: 'ready_to_run', RUNNING: 'running' }} }},
        runtime: {{ OnInstalledReason: {{ CHROME_UPDATE: 'chrome_update', INSTALL: 'install', SHARED_MODULE_UPDATE: 'shared_module_update', UPDATE: 'update' }}, OnRestartRequiredReason: {{ APP_UPDATE: 'app_update', OS_UPDATE: 'os_update', PERIODIC: 'periodic' }}, PlatformArch: {{ ARM: 'arm', ARM64: 'arm64', MIPS: 'mips', MIPS64: 'mips64', X86_32: 'x86-32', X86_64: 'x86-64' }}, PlatformNaclArch: {{ ARM: 'arm', MIPS: 'mips', MIPS64: 'mips64', X86_32: 'x86-32', X86_64: 'x86-64' }}, PlatformOs: {{ ANDROID: 'android', CROS: 'cros', LINUX: 'linux', MAC: 'mac', OPENBSD: 'openbsd', WIN: 'win' }}, RequestUpdateCheckStatus: {{ NO_UPDATE: 'no_update', THROTTLED: 'throttled', UPDATE_AVAILABLE: 'update_available' }} }},
        csi: () => {{}},
        loadTimes: () => ({{}})
    }});
    
    // Remove Playwright/automation markers
    delete window.__playwright;
    delete window.__pw_manual;
    delete window.__PW_inspect;
    
    // Override Notification
    if (typeof Notification !== 'undefined') {{
        defineProperty(Notification, 'permission', 'default');
    }}
    
    // Console - remove any automation warnings
    const originalWarn = console.warn;
    console.warn = function(...args) {{
        const msg = args[0]?.toString() || '';
        if (msg.includes('automation') || msg.includes('webdriver')) {{
            return; // Suppress
        }}
        return originalWarn.apply(console, args);
    }};
"""


def test_stealth_scripts():
    """Test stealth script generation."""
    from fingerprint_generator import FingerprintGenerator
    
    print("=" * 60)
    print("Testing Stealth Scripts Generator")
    print("=" * 60)
    
    # Generate fingerprint
    fp = FingerprintGenerator.generate(os_type="windows")
    
    # Generate scripts
    js_code = StealthScripts.generate_all(fp)
    
    print(f"\n1. Generated JavaScript length: {len(js_code)} characters")
    print(f"2. Lines of code: {js_code.count(chr(10))}")
    
    # Show preview
    print("\n3. Script preview (first 500 chars):")
    print("-" * 40)
    print(js_code[:500])
    print("-" * 40)
    
    # Check key components
    checks = [
        ("navigator.webdriver", "webdriver" in js_code),
        ("hardwareConcurrency", "hardwareConcurrency" in js_code),
        ("WebGL vendor", "UNMASKED_VENDOR" in js_code),
        ("Canvas noise", "toDataURL" in js_code),
        ("Audio noise", "AudioContext" in js_code),
        ("WebRTC", "RTCPeerConnection" in js_code),
        ("Timezone", "getTimezoneOffset" in js_code),
        ("Screen", "screen.width" in js_code or "screen, 'width'" in js_code),
    ]
    
    print("\n4. Component checks:")
    for name, passed in checks:
        status = "✅" if passed else "❌"
        print(f"   {status} {name}")
    
    print("\n" + "=" * 60)
    print("✅ Stealth Scripts Generator working!")
    print("=" * 60)
    
    return js_code


if __name__ == "__main__":
    test_stealth_scripts()
